spring:
  application:
    name: apibackend
  profiles:
    active: prod
  session:
    # 30 天过期
    timeout: 2592000
security:
  ignore:
    whites:
      - /web/**
      - /user/**
      - /blog/**
      - /interface/**
      - /email/**

