spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.126.87.57:3306/api?serverTimezone=Asia/Shanghai
    username: root
    password: 1345498749...
  redis:
      host: 101.126.87.57
      port: 6379
  application:
    name: apigateway
  profiles:
    active: dev
  cloud:
#    nacos:
#      server-addr: 182.92.7.24:8848
#      discovery:
#        namespace: dev
#        group: api-backend
#      config:
#        namespace: dev
#        file-extension: yaml
#        group: api-backend
    gateway:
      routes:
        - id: after_route
          uri: http://101.126.87.57:8102
          predicates:
            - Path=/interface/**
server:
  port: 8090

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
