spring:
  application:
    name: api
  profiles:
    active: prod
  session:
    # 30 天过期
    timeout: 2592000
security:
  ignore:
    whites:
      - /web/**
      - /user/**
      - /blog/**
      - /interface/**
      - /email/**

xxl:
  job:
    executor:
      appname: api_backend
      port: 7070
      logretentiondays: 30
      # 自己 ip
      ip:
    admin:
      addresses: http://127.0.0.1:7070/xxl-job-admin
    accessToken: default_token
file:
  downloadUrl: "E://workspace//"