spring:
  application:
    name: api
  profiles:
    active: prod
  session:
    # 30 天过期
    timeout: 2592000
security:
  ignore:
    whites:
      - /web/**
      - /user/**
      - /blog/**
      - /interface/**
      - /email/**
xxl:
  job:
    admin:
      address: http://localhost:8080/xxl-job-admin
    executor:
      appname: api
      address: http://localhost:8080
      logpath: /path/to/log
      logretentiondays: 30


